default:
  image: node:16.16.0

deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - npm install next@14
    - npm install --global vercel
    - npm run build --no-lint
    - vercel deploy --prod --token=$VERCEL_TOKEN --yes
