default:
  image: node:18-apline

deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - npm install -g npm@latest
    - npm install next
    - npm install --global vercel
    - npm run build -- --no-lint
    - vercel deploy --prod --token=$VERCEL_TOKEN --yes
